### PR TITLE
Export IGError and IGException constructors

### PR DESCRIPTION
**Pull request by glasserc**
This addresses prowdsponsor/ig#17.

### CODE REVIEW

**Comment by cdepillabout** [comment]
Since all you're doing is exposing new modules, I don't think you need to bump the version to `0.6`.  I think `0.5.1` is sufficient.  However, I could be wrong about this.

Other than that, this looks good to me.

**Comment by glasserc** [comment]
I wasn't sure if this project was following PVP or semver because the version number only has two digits in it. Commit https://github.com/prowdsponsor/ig/commit/9485b7217c8e3f65d1d4bc65b60552b535867cb4 bumps the second digit, even though it's backwards compatible, which I took as evidence that this project is following semver. I'd prefer to follow PVP if the maintainers prefer it, so just let me know which to do.

**Comment by meteficha** [comment]
@glasserc Version 0.3 included https://github.com/prowdsponsor/ig/commit/43c17cc9ea2998da9d15c77b81c7fe3fb627d931, which changes `User`.  

For this PR, `0.5.1` is fine :).

**Comment by glasserc** [comment]
I pushed a new commit which goes to 0.5.1 instead of 0.6. Thanks for the explanation!

**Comment by meteficha** [comment]
Thanks!  Released as `ig-0.5.1` :).

**Pull request merged**
